name: granule-benchmark
version: '0.8.2.0'
synopsis: The Granule synthesis benchmarking tool
author: Dominic Orchard, Vilem-Benjamin Liepelt, Harley Eades III, Jack Hughes
copyright: 2018-2023 authors
license: BSD3
github: granule-project/granule
dependencies:
- base >=4.10 && <5

ghc-options:
- -O2

executables:
  grenchmark:
    main: Language/Granule/Main.hs
    source-dirs: src
    ghc-options: -main-is Language.Granule.Main
    dependencies:
    - granule-interpreter
    - granule-frontend
    - strict 
    - directory
    - process
    - time
    - text
    - filepath 