name: granule-frontend
version: '0.7.7.1'
synopsis: The Granule abstract-syntax-tree, parser and type checker libraries
author: Dominic Orchard, Vilem-Benjamin Liepelt, Harley Eades III, Preston Keel
copyright: 2018 authors
license: BSD3
github: granule-project/granule
dependencies:
- base >=4.10 && <5

ghc-options:
- -O0
- -Wall
- -Werror
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wno-unused-matches
- -Wno-name-shadowing
- -Wno-type-defaults

default-extensions:
- ImplicitParams
- ViewPatterns
- LambdaCase
- TupleSections
- NamedFieldPuns

library:
  source-dirs: src
  # when:
  # - condition: flag(dev)
  #   then:
  #     ghc-options: -O0 -W -Werror -Wno-unused-matches
  #   else:
  #     ghc-options: -O3 -Wall -Werror -Wno-unused-matches
  build-tools:
  - alex
  - happy
  exposed-modules:
  - Data.Bifunctor.Foldable
  - Language.Granule.Checker.Checker
  - Language.Granule.Checker.Coeffects
  - Language.Granule.Checker.Constraints
  - Language.Granule.Checker.Constraints.SNatX
  - Language.Granule.Checker.Flatten
  - Language.Granule.Checker.KindsHelpers
  - Language.Granule.Checker.LaTeX
  - Language.Granule.Checker.Monad
  - Language.Granule.Checker.Patterns
  - Language.Granule.Checker.Predicates
  - Language.Granule.Checker.Primitives
  - Language.Granule.Checker.SubstitutionContexts
  - Language.Granule.Checker.Substitution
  - Language.Granule.Checker.Types
  - Language.Granule.Syntax.Def
  - Language.Granule.Syntax.Expr
  - Language.Granule.Syntax.Helpers
  - Language.Granule.Syntax.FirstParameter
  - Language.Granule.Syntax.Annotated
  - Language.Granule.Syntax.Identifiers
  - Language.Granule.Syntax.Lexer
  - Language.Granule.Syntax.Parser
  - Language.Granule.Syntax.Pattern
  - Language.Granule.Syntax.Pretty
  - Language.Granule.Syntax.Preprocessor
  - Language.Granule.Syntax.Preprocessor.Ascii
  - Language.Granule.Syntax.Preprocessor.Latex
  - Language.Granule.Syntax.Preprocessor.Markdown
  - Language.Granule.Syntax.Span
  - Language.Granule.Syntax.Type
  - Language.Granule.Synthesis.Splitting
  - Language.Granule.Context
  - Language.Granule.Utils
  dependencies:
  - array
  - containers
  - mtl >=2.2.1
  - sbv >=8.0
  - transformers >=0.5
  - text
  - time
  - Glob
  - filepath
  - bifunctors
  - raw-strings-qq
  - text-replace
  - directory

tests:
  frontend-spec:
    main: Spec.hs
    source-dirs: tests/hspec
    ghc-options: -fno-warn-partial-type-signatures
    dependencies:
    # - filemanip
    # - directory
    - granule-frontend
    - hspec
    - QuickCheck
    - mtl
    - containers
    - transformers >=0.5
    - bifunctors
#  zfrontend-doctest: # the "z" is to make them run after hspec
#    main: doctest.hs
#    source-dirs: tests
#    dependencies:
#    - doctest
#    - granule-frontend
#    ghc-options: -threaded
