resolver: lts-22.44
packages:
- frontend/
- interpreter/
- repl/
- server/
- compiler/
- runtime/
- benchmark/

# Dependency packages to be pulled from upstream that are not in the resolver
extra-deps:
- git: https://github.com/mixphix/text-replace.git
  commit: 301b45914229f40d715268a825b38524bc05e5d8
  subdirs:
  - text-replace
- syz-0.2.0.0
- git: https://github.com/jackohughes/haskell-src-exts
  commit: 5c2647fa0746bdac046897f5a6b7e4f5ef3afa79

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.4"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building

## Superfluous?
# extra-include-dirs:
# - /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/ffi

# extra-lib-dirs: [/path/to/dir]




# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
