-- boolean-like interface
interface BoolI a where
  bAnd : a -> a -> a;
  bOr  : a -> a -> a;
  bNot : a -> a

-- non-interface function defined only in terms
-- of interface functions
bXOR : forall {a : Type} . {BoolI a} => a [2] -> a [2] -> a
bXOR [x] [y] = bAnd (bOr x y) (bNot (bAnd x y))

data BoolTy = F | T

instance BoolI BoolTy where
  bAnd T T = T;
  bAnd _ _ = F;

  bOr F F = F;
  bOr _ _ = T;

  bNot T = F;
  bNot _ = T
