import Bool

readFile : String -> String <IO>
readFile filename =
  let h       <- openFile filename ReadMode;
      (h, cs) <- getCharsUntilEnd h;
      ()      <- hClose h
  in pure cs

getCharsUntilEnd : Handle -> (Handle, String) <IO>
getCharsUntilEnd h =
    let (h, b) <- isEOF h
    in case b of
        True -> pure (h, "");
        False ->
            let (h, c) <- hGetChar h;
                (h, cs) <- getCharsUntilEnd h
            in pure (h, stringAppend (showChar c) cs)
