------
--- Module: Sequence
--- Description: Unsized sequences (lists)
--- Authors: Dominic Orchard
--- License: BSD3
--- Copyright: (c) Authors 2018
--- Issue-tracking: https://github.com/dorchard/granule/issues
--- Repository: https://github.com/dorchard/granule
------

data Sequence a where
  Empty : Sequence a;
  Next : a -> Sequence a -> Sequence a

length : forall a : Type . (Sequence a) |0| -> Int
length xs =
  case xs of
    [Empty]       -> 0;
    [Next _ xs] -> 1 + length |xs|
