name: granule-repl
version: '0.9.3.0'
synopsis: The Granule interactive interpreter (grepl)
author: Dominic Orchard, Vilem-Benjamin Liepelt, Harley Eades III, Preston Keel
copyright: 2019 authors
license: BSD3
github: dorchard/granule
dependencies:
- base >=4.10 && <5

executables:
  grepl:
    main: Language/Granule/Main.hs
    source-dirs: app
    ghc-options: -O3 -W -Werror -Wno-unused-matches
    # exposed-modules:
    # - Language.Granule.Queue
    # - Language.Granule.ReplError
    # - Language.Granule.ReplParser
    dependencies:
    - granule-interpreter
    - granule-frontend
    - containers
    - Glob
    - directory
    - filemanip
    - filepath
    - haskeline
    - mtl >=2.2.1
    - parsec
    - text
    - transformers >=0.5
    - clock >= 0.8
