-- Prelude library for Gram

id : Int -> Int
id x = x

const : Int -> |Int| 0 -> Int
const x _ = x

if0 : Int -> Int -> Int -> Int
if0 g x y = case g of
                0 -> x;
                n -> y

-- Coeffectful composition
comp : (|Int| c -> Int) -> (|Int| d -> Int) -> |Int| (c * d) -> Int
comp f g |x| = g |(f |x|)|

-- Coeffectful application
app : (|Int| c -> Int) -> |Int| c -> Int
app f x = f x

flip : (Int -> Int -> Int) -> Int -> Int -> Int
flip f x y = f y x
