publicOk : forall {a : Type} .  a [Lo] -> a
publicOk [x] = x

-- Ill-typed
-- privBad : forall {a : Type} .  a [Hi] -> a
-- privBad [x] = x

keepPrivate : forall {a : Type} . a [Hi] -> a [Hi]
keepPrivate [x] = [x]

data Bool = True | False

publicNot : Bool [Lo] -> Bool
publicNot [True] = False;
publicNot [False] = True

-- Ill-typed
-- privateNot : Bool [Hi] -> Bool
-- privateNot [True] = False;
-- privateNot [False] = True
