-- The following examples are inspired by those in
-- "FlowCaml in a Nutshell" (Simonet, 2003)

data People = Alice | Bob | Charlie

x1 : Int [{Alice}.]
x1 = [42]

x2 : Int [{Bob}.]
x2 = [53]

x3 : Int [{Charlie}.]
x3 = [11]

x1px1 : Int [{Alice}.]
x1px1 =
  let [x] = x1 in [x + x]

x1px2 : Int [{Alice, Bob}.]
x1px2 =
  let [x] = x1 in
  let [y] = x2 in [x + y]

x1tx2tx3 : Int [{Alice, Bob, Charlie}.]
x1tx2tx3 =
  let [x] = x1 in
  let [y] = x2 in
  let [z] = x3 in [x * y * z]
