-- last checked 2019-01-07 by @buggymcbugfix

import Vec
import Bool

-- Type error: work-in-progress/filter.gr: :7:1:
--   Definition 'filter'is Falsifiable. Counter-example:
--   k_2 = 2 :: Integer
--   n_1 = 0 :: Integer
-- Failed
filter : ∀ a : Type, n : Nat, k : Nat
       . (a → Bool) [n+k] → Vec (n + k) (a [0..2]) → Vec n a
filter [_] Nil = Nil;
filter [p] (Cons [x] xs) = if p x then Cons x (filter [p] xs) else filter [p] xs
