import File
import Sequence

-- openFile :: String -> IOMode -> IO Handle
-- hGetChar :: Handle -> IO Char
-- hClose :: Handle -> IO ()

-- openFile : String -> IOMode -> Handle
-- hGetChar :: Handle -> (Handle, Char)
-- hPutChar :: Handle -> Char -> Handle
-- hClose :: Handle -> ()

main : IO (Sequence Char)
main =
    let h0       <- openFile "foo" ReadMode;
        (h1, c)  <- hGetChar h0;
        (h2, c') <- hGetChar h1;
        ()       <- hClose h2
    in pure (Next c (Next c' Empty))
