name: granule-interpreter
version: '0.7.1.1'
synopsis: The Granule interpreter
author: Dominic Orchard, Vilem-Benjamin Liepelt, Harley Eades III, Preston Keel
copyright: 2018 authors
license: BSD3
github: dorchard/granule
dependencies:
- base >=4.10 && <5

library:
  source-dirs: src
  ghc-options: -O0 -W -Werror -Wno-unused-matches -Wwarn=incomplete-patterns
  # when:
  # - condition: flag(dev)
  #   then:
  #     ghc-options: -O0 -W -Werror -Wno-unused-matches
  #   else:
  #     ghc-options: -O3 -w
  exposed-modules:
  - Language.Granule.Eval
  - Language.Granule.Desugar
  dependencies:
  - granule-frontend
  - mtl >=2.2.1
  - text

executables:
  gr:
    main: Language/Granule/Interpreter/Main.hs
    source-dirs: app
    ghc-options: -O0 -W -Werror -Wno-unused-matches
    dependencies:
    - granule-frontend
    - granule-interpreter
    - directory
    - Glob
    - optparse-applicative
