name: granule-interpreter
version: '0.7.4.1'
synopsis: The Granule interpreter
author: Dominic Orchard, Vilem-Benjamin Liepelt, Harley Eades III, Preston Keel
copyright: 2019 authors
license: BSD3
github: dorchard/granule
dependencies:
- base >=4.10 && <5
- directory
- extra
- filepath
- gitrev
- Glob
- granule-frontend
- mtl >=2.2.1
- optparse-applicative
- text
default-extensions:
- LambdaCase
- RecordWildCards
- ImplicitParams
- ScopedTypeVariables
- OverloadedStrings

ghc-options:
- -O0
- -Wall
- -Werror
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wno-unused-matches
- -Wno-name-shadowing
- -Wno-type-defaults

library:
  source-dirs: src
  # when:
  # - condition: flag(dev)
  #   then:
  #     ghc-options: -O0 -W -Werror -Wno-unused-matches
  #   else:
  #     ghc-options: -O3 -w
  exposed-modules:
  - Language.Granule.Interpreter
  - Language.Granule.Interpreter.Eval
  - Language.Granule.Interpreter.Desugar
  - Language.Granule.Interpreter.Type

executables:
  gr:
    main: Language/Granule/Interpreter.hs
    source-dirs: src
    ghc-options: -main-is Language.Granule.Interpreter
    dependencies:
    - granule-interpreter

tests:
  gr-golden:
    main: Golden.hs
    source-dirs: tests
    dependencies:
    - Diff
    - granule-interpreter
    - strict
    - tasty
    - tasty-golden
